
# ZHAW thesis template

In @sec-exercieses you developped a Quarto based document in a bottom up approach. This was very important for you to get a good understanding of how Quarto works. However the output did not look at all like a document you could submit as a thesis.

In this chapter, we will introduce a Quarto extension we developped that will turn your quarto document into a PDF that [meets the ZHAW LSFM requirements]{.underline}. This extension uses [Typst](https://typst.app) as a backend to generate a pdf. 

:::{.callout-note}

All information on the thesis template / extension can be found here:

<https://zhaw-lsfm.github.io/quarto-thesis/>

:::


**What do we mean by backend?**

Quarto does not have a custom PDF renderer. But Quarto is based on pandoc, which means that Quarto files are converted to a markup language that *does* have a PDF renderer. There are two choices:

- **Latex**: The classical approach to rendering pdfs. [Very old, very mature, but very complex]{.underline}. 
- **Typst**: A new markup language designed with an improved syntax and much faster compilation. It has a young, vibrant and growing community and we believe [Typst will replace LaTeX in the long run]{.underline}. 


```{mermaid}
%%| fig-cap: "Quarto files are either converted to typst or latex to create a pdf. We recommend using typst."
%%| label: fig-rendering
graph LR
    Q1[Quarto] --> L[LaTeX Markup] --> P1[PDF]
    Q1 --> T[Typst Markup] --> P1[PDF]
```


<!-- Typst is an OpenSource CLI program, but it also has a Webinterface with live preview, similar to Overleaf. -->


## Tasks

```{r}
#| echo: false
counter <- 0
nxt <- function() {
  counter <<- counter + 1
  paste("Task",counter)
}
```


### `r nxt()`:  Change output format

Open the document from @sec-exercieses. Change the output format in the metadata to `typst` and preview your document (`quarto preview index.qmd`). If you already have a preview session running in the terminal, you will need to interrupt it with <kbd>Ctrl</kbd>+<kbd>C</kbd> and then run the preview command.

You can also give the latex renderer a try by compiling to `format: pdf`. 



::: {.panel-tabset}

## Before

```{.markdown}
---
title: "Robust Regression and Outlier Detection" 
subtitle: "Chapter 2: Simple Regression"
author: 
  - Peter J. Rousseeuw
  - Annick M. Leroy
date: "1987-10-19"
format: html
---
``` 



## After

```{.markdown}
---
title: "Robust Regression and Outlier Detection" 
subtitle: "Chapter 2: Simple Regression"
author: 
  - Peter J. Rousseeuw
  - Annick M. Leroy
date: "1987-10-19"
format: typst
---
``` 

:::


### `r nxt()`:  Install the extension 

To facilitate the writing of your thesis, we've created a ZHAW LSFM template that meets the requirements made by the department. We've packaged this template as a [Quarto extension](https://quarto.org/docs/extensions/). 


Quarto has a convenient way to distribute extension. Since we host our code [on GitHub](https://github.com/zhaw-lsfm/quarto-thesis), you can simply install the extension using the GitHub Username/oganisation like so:

```{.bash}
quarto use template zhaw-lsfm/quarto-thesis

# (we recommend you use a new, empty folder for this step and 
# answer the followup questions with `Yes`)
``` 


This will create the following folder structure on your computer:

```{.bash}
├── _extensions          # <1>
│   └── ...              # <1>
├── references.bib
└── SOMENAME.qmd         # <2>


```

1. The folder `extensions` is not important right now
2. A Quarto file with the same name as the parent folder is your starter file!

### `r nxt()`:  Preview the document

Now, run `quarto preview SOMENAME.qmd` to get a first look at how your output looks like. Change the YAML metadata to meet your thesis and check the output. 


### `r nxt()`:  Read the template manual


We've written a manual on our template / extension. Have a look at it here

<https://zhaw-lsfm.github.io/quarto-thesis/>


**Now, you are ready to write your thesis!**




